import { Repository, Category, BatteryCategory } from '@/types';

export const mockRepositories: Repository[] = [
  {
    id: 1,
    name: 'BMS-Master',
    full_name: 'bms-community/BMS-Master',
    html_url: 'https://github.com/bms-community/BMS-Master',
    description: 'An advanced Battery Management System for Li-ion.',
    owner: { login: 'bms-community', avatar_url: '' },
    stars: 1500,
    forks: 300,
    topics: ['bms', 'li-ion', 'embedded'],
    category: BatteryCategory.BMS,
    language: 'C++',
    license: { name: 'MIT' },
    updated_at: '2023-10-01',
    archived: false,
  },
  {
    id: 2,
    name: 'PyBaMM',
    full_name: 'pybamm-team/PyBaMM',
    html_url: 'https://github.com/pybamm-team/PyBaMM',
    description: 'Python Battery Mathematical Modelling (PyBaMM) for simulating battery models.',
    owner: { login: 'pybamm-team', avatar_url: '' },
    stars: 2100,
    forks: 450,
    topics: ['python', 'simulation', 'electrochemistry', 'battery-modeling'],
    category: BatteryCategory.CELL_DESIGN,
    language: 'Python',
    license: { name: 'BSD-3-Clause' },
    updated_at: '2024-07-10',
    archived: false,
  },
  {
    id: 3,
    name: 'Electrolyte-DB',
    full_name: 'e-chem/Electrolyte-DB',
    html_url: 'https://github.com/e-chem/Electrolyte-DB',
    description: 'A database of electrolyte properties for battery research.',
    owner: { login: 'e-chem', avatar_url: '' },
    stars: 450,
    forks: 90,
    topics: ['database', 'materials-science', 'electrochemistry'],
    category: BatteryCategory.MATERIALS,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2023-11-05',
    archived: false,
  },
  {
    id: 4,
    name: 'Battery-Recycle-Net',
    full_name: 'recycle-ai/Battery-Recycle-Net',
    html_url: 'https://github.com/recycle-ai/Battery-Recycle-Net',
    description: 'Deep learning models for identifying recyclable battery components.',
    owner: { login: 'recycle-ai', avatar_url: '' },
    stars: 600,
    forks: 120,
    topics: ['deep-learning', 'recycling', 'sustainability'],
    category: BatteryCategory.RECYCLING,
    language: 'Python',
    license: { name: 'Apache-2.0' },
    updated_at: '2023-10-22',
    archived: false,
  },
  {
    id: 5,
    name: 'Open-BMS-Firmware',
    full_name: 'open-bms/Open-BMS-Firmware',
    html_url: 'https://github.com/open-bms/Open-BMS-Firmware',
    description: 'Open source firmware for various BMS hardware.',
    owner: { login: 'open-bms', avatar_url: '' },
    stars: 1200,
    forks: 250,
    topics: ['firmware', 'bms', 'c++'],
    category: BatteryCategory.BMS,
    language: 'C++',
    license: { name: 'GPL-3.0' },
    updated_at: '2023-11-10',
    archived: false,
  },
  // Adding a few more with the correct structure for completeness
  {
    id: 6,
    name: 'Cell-Analyzer',
    full_name: 'cell-gurus/Cell-Analyzer',
    html_url: 'https://github.com/cell-gurus/Cell-Analyzer',
    description: 'Tools for analyzing battery cell test data.',
    owner: { login: 'cell-gurus', avatar_url: '' },
    stars: 300,
    forks: 75,
    topics: ['testing', 'data-analysis', 'python'],
    category: BatteryCategory.TESTING,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2023-08-30',
    archived: false,
  },
  {
    id: 7,
    name: 'SimBAn',
    full_name: 'simban-dev/SimBAn',
    html_url: 'https://github.com/simban-dev/SimBAn',
    description: 'A Simulink-based Battery Analysis tool for performance evaluation.',
    owner: { login: 'simban-dev', avatar_url: '' },
    stars: 180,
    forks: 50,
    topics: ['simulink', 'battery-testing', 'matlab'],
    category: BatteryCategory.TESTING,
    language: 'MATLAB',
    license: { name: 'MIT' },
    updated_at: '2024-06-15',
    archived: true,
  },
  {
    id: 8,
    name: 'batpaq',
    full_name: 'NREL/batpaq',
    html_url: 'https://github.com/NREL/batpaq',
    description: 'A tool for creating and analyzing battery pack geometries.',
    owner: { login: 'NREL', avatar_url: '' },
    stars: 250,
    forks: 60,
    topics: ['battery-pack', 'design', 'thermal-analysis'],
    category: BatteryCategory.PACK_MANUFACTURING,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2024-05-20',
    archived: false,
  }
];

export const mockCategories: Category[] = [
    { id: 'BMS', name: 'Battery Management System (BMS)', description: 'Projects related to managing and monitoring battery packs.', repositories: 4 },
    { id: 'CELL_DESIGN', name: 'Cell Design & Simulation', description: 'Tools for designing and simulating battery cells.', repositories: 2 },
    { id: 'MATERIALS', name: 'Materials Science', description: 'Research and data on battery materials.', repositories: 2 },
    { id: 'RECYCLING', name: 'Recycling & Sustainability', description: 'Initiatives for recycling and sustainable battery lifecycles.', repositories: 2 },
    { id: 'TESTING', name: 'Testing & Analytics', description: 'Software and hardware for testing battery performance.', repositories: 3 },
    { id: 'PACK_MANUFACTURING', name: 'Pack Manufacturing', description: 'Projects focused on the manufacturing process of battery packs.', repositories: 2 },
]; 