import type { Repository, Category } from '@/types';

export const mockRepositories: Repository[] = [
  { id: 1, name: 'BMS-Master', stars: 1500, forks: 300, description: 'An advanced Battery Management System for Li-ion.', category: 'BMS', url: 'https://github.com/bms-community/BMS-Master', owner: 'bms-community', ownerUrl: 'https://github.com/bms-community', lastUpdate: '2023-10-01', topics: ['bms', 'li-ion', 'embedded'] },
  { id: 2, name: 'PyBaMM', stars: 2100, forks: 450, description: 'Python Battery Mathematical Modelling (PyBaMM) for simulating battery models.', category: 'CELL_DESIGN', url: 'https://github.com/pybamm-team/PyBaMM', owner: 'pybamm-team', ownerUrl: 'https://github.com/pybamm-team', lastUpdate: '2024-07-10', topics: ['python', 'simulation', 'electrochemistry', 'battery-modeling'] },
  { id: 3, name: 'Electrolyte-DB', stars: 450, forks: 90, description: 'A database of electrolyte properties for battery research.', category: 'MATERIALS', url: 'https://github.com/e-chem/Electrolyte-DB', owner: 'e-chem', ownerUrl: 'https://github.com/e-chem', lastUpdate: '2023-11-05', topics: ['database', 'materials-science', 'electrochemistry'] },
  { id: 4, name: 'Battery-Recycle-Net', stars: 600, forks: 120, description: 'Deep learning models for identifying recyclable battery components.', category: 'RECYCLING', url: 'https://github.com/recycle-ai/Battery-Recycle-Net', owner: 'recycle-ai', ownerUrl: 'https://github.com/recycle-ai', lastUpdate: '2023-10-22', topics: ['deep-learning', 'recycling', 'sustainability'] },
  { id: 5, name: 'Open-BMS-Firmware', stars: 1200, forks: 250, description: 'Open source firmware for various BMS hardware.', category: 'BMS', url: 'https://github.com/open-bms/Open-BMS-Firmware', owner: 'open-bms', ownerUrl: 'https://github.com/open-bms', lastUpdate: '2023-11-10', topics: ['firmware', 'bms', 'c++'] },
  { id: 6, name: 'Cell-Analyzer', stars: 300, forks: 75, description: 'Tools for analyzing battery cell test data.', category: 'TESTING', url: 'https://github.com/cell-gurus/Cell-Analyzer', owner: 'cell-gurus', ownerUrl: 'https://github.com/cell-gurus', lastUpdate: '2023-08-30', topics: ['testing', 'data-analysis', 'python'] },
  { id: 7, name: 'SimBAn', stars: 180, forks: 50, description: 'A Simulink-based Battery Analysis tool for performance evaluation.', category: 'TESTING', url: 'https://github.com/simban-dev/SimBAn', owner: 'simban-dev', ownerUrl: 'https://github.com/simban-dev', lastUpdate: '2024-06-15', topics: ['simulink', 'battery-testing', 'matlab'] },
  { id: 8, name: 'batpaq', stars: 250, forks: 60, description: 'A tool for creating and analyzing battery pack geometries.', category: 'PACK_MANUFACTURING', url: 'https://github.com/NREL/batpaq', owner: 'NREL', ownerUrl: 'https://github.com/NREL', lastUpdate: '2024-05-20', topics: ['battery-pack', 'design', 'thermal-analysis'] },
  { id: 9, name: 'impedance.py', stars: 410, forks: 120, description: 'A Python library for analyzing electrochemical impedance spectroscopy (EIS) data.', category: 'TESTING', url: 'https://github.com/ECSHackWeek/impedance.py', owner: 'ECSHackWeek', ownerUrl: 'https://github.com/ECSHackWeek', lastUpdate: '2024-07-01', topics: ['eis', 'electrochemistry', 'python', 'data-analysis'] },
  { id: 10, name: 'OpenBESS', stars: 150, forks: 40, description: 'BigData and ML empowered intelligent battery energy storage system.', category: 'BMS', url: 'https://github.com/zhangjinpeng87/OpenBESS', owner: 'zhangjinpeng87', ownerUrl: 'https://github.com/zhangjinpeng87', lastUpdate: '2024-04-18', topics: ['bess', 'big-data', 'machine-learning', 'iot'] },
  { id: 11, name: 'Li-Ion-Battery-Research', stars: 80, forks: 25, description: 'Collection of research papers and models on Li-Ion batteries.', category: 'MATERIALS', url: 'https://github.com/research-hub/Li-Ion-Battery-Research', owner: 'research-hub', ownerUrl: 'https://github.com/research-hub', lastUpdate: '2024-02-28', topics: ['research', 'li-ion', 'materials-science'] },
  { id: 12, name: 'Second-Life-BMS', stars: 320, forks: 80, description: 'BMS designed for second-life battery applications in energy storage.', category: 'RECYCLING', url: 'https://github.com/second-life-bms/Second-Life-BMS', owner: 'second-life-bms', ownerUrl: 'https://github.com/second-life-bms', lastUpdate: '2024-06-30', topics: ['second-life-battery', 'bms', 'energy-storage', 'sustainability'] },
  { id: 13, name: 'Cathode-Design-Toolkit', stars: 210, forks: 55, description: 'Computational tools for designing next-generation cathode materials.', category: 'CELL_DESIGN', url: 'https://github.com/cathode-designers/Cathode-Design-Toolkit', owner: 'cathode-designers', ownerUrl: 'https://github.com/cathode-designers', lastUpdate: '2024-03-12', topics: ['cathode', 'materials-design', 'simulation'] },
  { id: 14, name: 'ENNOID-BMS', stars: 580, forks: 150, description: 'High performance, modular and open source BMS for various applications.', category: 'BMS', url: 'https://github.com/ennoid/ENNOID-BMS', owner: 'ennoid', ownerUrl: 'https://github.com/ennoid', lastUpdate: '2024-07-15', topics: ['bms', 'modular', 'high-performance', 'hardware'] },
  { id: 15, name: 'Thermal-Modeling-Framework', stars: 190, forks: 45, description: 'A framework for thermal modeling and simulation of battery packs.', category: 'PACK_MANUFACTURING', url: 'https://github.com/thermal-sim/Thermal-Modeling-Framework', owner: 'thermal-sim', ownerUrl: 'https://github.com/thermal-sim', lastUpdate: '2024-05-01', topics: ['thermal-modeling', 'simulation', 'battery-pack', 'ansys'] },
];

export const mockCategories: Category[] = [
    { id: 'BMS', name: 'Battery Management System (BMS)', description: 'Projects related to managing and monitoring battery packs.', repositories: 4 },
    { id: 'CELL_DESIGN', name: 'Cell Design & Simulation', description: 'Tools for designing and simulating battery cells.', repositories: 2 },
    { id: 'MATERIALS', name: 'Materials Science', description: 'Research and data on battery materials.', repositories: 2 },
    { id: 'RECYCLING', name: 'Recycling & Sustainability', description: 'Initiatives for recycling and sustainable battery lifecycles.', repositories: 2 },
    { id: 'TESTING', name: 'Testing & Analytics', description: 'Software and hardware for testing battery performance.', repositories: 3 },
    { id: 'PACK_MANUFACTURING', name: 'Pack Manufacturing', description: 'Projects focused on the manufacturing process of battery packs.', repositories: 2 },
]; 