import { Repository, Category, BatteryCategory } from '@/types';

export const mockRepositories: Repository[] = [
  {
    id: 1,
    name: 'BMS-Master',
    full_name: 'bms-community/BMS-Master',
    html_url: 'https://github.com/bms-community/BMS-Master',
    description: 'An advanced Battery Management System for Li-ion.',
    owner: { login: 'bms-community', avatar_url: '' },
    stars: 1500,
    forks: 300,
    topics: ['bms', 'li-ion', 'embedded'],
    category: BatteryCategory.BMS,
    language: 'C++',
    license: { name: 'MIT' },
    updated_at: '2023-10-01',
    created_at: '2020-01-01',
    pushed_at: '2023-10-01',
    stargazers_count: 1500,
    forks_count: 300,
  },
  {
    id: 2,
    name: 'PyBaMM',
    full_name: 'pybamm-team/PyBaMM',
    html_url: 'https://github.com/pybamm-team/PyBaMM',
    description: 'Python Battery Mathematical Modelling (PyBaMM) for simulating battery models.',
    owner: { login: 'pybamm-team', avatar_url: '' },
    stars: 2100,
    forks: 450,
    topics: ['python', 'simulation', 'electrochemistry', 'battery-modeling'],
    category: BatteryCategory.CELL_DESIGN,
    language: 'Python',
    license: { name: 'BSD-3-Clause' },
    updated_at: '2024-07-10',
    created_at: '2018-01-01',
    pushed_at: '2024-07-10',
    stargazers_count: 2100,
    forks_count: 450,
  },
  {
    id: 3,
    name: 'Electrolyte-DB',
    full_name: 'e-chem/Electrolyte-DB',
    html_url: 'https://github.com/e-chem/Electrolyte-DB',
    description: 'A database of electrolyte properties for battery research.',
    owner: { login: 'e-chem', avatar_url: '' },
    stars: 450,
    forks: 90,
    topics: ['database', 'materials-science', 'electrochemistry'],
    category: BatteryCategory.MATERIALS,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2023-11-05',
    created_at: '2019-01-01',
    pushed_at: '2023-11-05',
    stargazers_count: 450,
    forks_count: 90,
  },
  {
    id: 4,
    name: 'Battery-Recycle-Net',
    full_name: 'recycle-ai/Battery-Recycle-Net',
    html_url: 'https://github.com/recycle-ai/Battery-Recycle-Net',
    description: 'Deep learning models for identifying recyclable battery components.',
    owner: { login: 'recycle-ai', avatar_url: '' },
    stars: 600,
    forks: 120,
    topics: ['deep-learning', 'recycling', 'sustainability'],
    category: BatteryCategory.RECYCLING,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2023-10-22',
    created_at: '2020-01-01',
    pushed_at: '2023-10-22',
    stargazers_count: 600,
    forks_count: 120,
  },
  {
    id: 5,
    name: 'Open-BMS-Firmware',
    full_name: 'open-bms/Open-BMS-Firmware',
    html_url: 'https://github.com/open-bms/Open-BMS-Firmware',
    description: 'Open source firmware for various BMS hardware.',
    owner: { login: 'open-bms', avatar_url: '' },
    stars: 1200,
    forks: 250,
    topics: ['firmware', 'bms', 'c++'],
    category: BatteryCategory.BMS,
    language: 'C++',
    license: { name: 'MIT' },
    updated_at: '2023-11-10',
    created_at: '2018-01-01',
    pushed_at: '2023-11-10',
    stargazers_count: 1200,
    forks_count: 250,
  },
  {
    id: 6,
    name: 'Cell-Analyzer',
    full_name: 'cell-gurus/Cell-Analyzer',
    html_url: 'https://github.com/cell-gurus/Cell-Analyzer',
    description: 'Tools for analyzing battery cell test data.',
    owner: { login: 'cell-gurus', avatar_url: '' },
    stars: 300,
    forks: 75,
    topics: ['testing', 'data-analysis', 'python'],
    category: BatteryCategory.TESTING,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2023-08-30',
    created_at: '2019-01-01',
    pushed_at: '2023-08-30',
    stargazers_count: 300,
    forks_count: 75,
  },
  {
    id: 7,
    name: 'SimBAn',
    full_name: 'simban-dev/SimBAn',
    html_url: 'https://github.com/simban-dev/SimBAn',
    description: 'A Simulink-based Battery Analysis tool for performance evaluation.',
    owner: { login: 'simban-dev', avatar_url: '' },
    stars: 180,
    forks: 50,
    topics: ['simulink', 'battery-testing', 'matlab'],
    category: BatteryCategory.TESTING,
    language: 'MATLAB',
    license: { name: 'MIT' },
    updated_at: '2024-06-15',
    created_at: '2018-01-01',
    pushed_at: '2024-06-15',
    stargazers_count: 180,
    forks_count: 50,
  },
  {
    id: 8,
    name: 'batpaq',
    full_name: 'NREL/batpaq',
    html_url: 'https://github.com/NREL/batpaq',
    description: 'A tool for creating and analyzing battery pack geometries.',
    owner: { login: 'NREL', avatar_url: '' },
    stars: 250,
    forks: 60,
    topics: ['battery-pack', 'design', 'thermal-analysis'],
    category: BatteryCategory.PACK_MANUFACTURING,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2024-05-20',
    created_at: '2019-01-01',
    pushed_at: '2024-05-20',
    stargazers_count: 250,
    forks_count: 60,
  },
  {
    id: 9,
    name: 'impedance.py',
    full_name: 'ECSHackWeek/impedance.py',
    html_url: 'https://github.com/ECSHackWeek/impedance.py',
    description: 'A Python library for analyzing electrochemical impedance spectroscopy (EIS) data.',
    owner: { login: 'ECSHackWeek', avatar_url: '' },
    stars: 410,
    forks: 120,
    topics: ['eis', 'electrochemistry', 'python', 'data-analysis'],
    category: BatteryCategory.TESTING,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2024-07-01',
    created_at: '2018-01-01',
    pushed_at: '2024-07-01',
    stargazers_count: 410,
    forks_count: 120,
  },
  {
    id: 10,
    name: 'OpenBESS',
    full_name: 'zhangjinpeng87/OpenBESS',
    html_url: 'https://github.com/zhangjinpeng87/OpenBESS',
    description: 'BigData and ML empowered intelligent battery energy storage system.',
    owner: { login: 'zhangjinpeng87', avatar_url: '' },
    stars: 150,
    forks: 40,
    topics: ['bess', 'big-data', 'machine-learning', 'iot'],
    category: BatteryCategory.BMS,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2024-04-18',
    created_at: '2019-01-01',
    pushed_at: '2024-04-18',
    stargazers_count: 150,
    forks_count: 40,
  },
  {
    id: 11,
    name: 'Li-Ion-Battery-Research',
    full_name: 'research-hub/Li-Ion-Battery-Research',
    html_url: 'https://github.com/research-hub/Li-Ion-Battery-Research',
    description: 'Collection of research papers and models on Li-Ion batteries.',
    owner: { login: 'research-hub', avatar_url: '' },
    stars: 80,
    forks: 25,
    topics: ['research', 'li-ion', 'materials-science'],
    category: BatteryCategory.MATERIALS,
    language: 'N/A',
    license: { name: 'MIT' },
    updated_at: '2024-02-28',
    created_at: '2019-01-01',
    pushed_at: '2024-02-28',
    stargazers_count: 80,
    forks_count: 25,
  },
  {
    id: 12,
    name: 'Second-Life-BMS',
    full_name: 'second-life-bms/Second-Life-BMS',
    html_url: 'https://github.com/second-life-bms/Second-Life-BMS',
    description: 'BMS designed for second-life battery applications in energy storage.',
    owner: { login: 'second-life-bms', avatar_url: '' },
    stars: 320,
    forks: 80,
    topics: ['second-life-battery', 'bms', 'energy-storage', 'sustainability'],
    category: BatteryCategory.RECYCLING,
    language: 'C++',
    license: { name: 'MIT' },
    updated_at: '2024-06-30',
    created_at: '2019-01-01',
    pushed_at: '2024-06-30',
    stargazers_count: 320,
    forks_count: 80,
  },
  {
    id: 13,
    name: 'Cathode-Design-Toolkit',
    full_name: 'cathode-designers/Cathode-Design-Toolkit',
    html_url: 'https://github.com/cathode-designers/Cathode-Design-Toolkit',
    description: 'Computational tools for designing next-generation cathode materials.',
    owner: { login: 'cathode-designers', avatar_url: '' },
    stars: 210,
    forks: 55,
    topics: ['cathode', 'materials-design', 'simulation'],
    category: BatteryCategory.CELL_DESIGN,
    language: 'Python',
    license: { name: 'MIT' },
    updated_at: '2024-03-12',
    created_at: '2019-01-01',
    pushed_at: '2024-03-12',
    stargazers_count: 210,
    forks_count: 55,
  },
  {
    id: 14,
    name: 'ENNOID-BMS',
    full_name: 'ennoid/ENNOID-BMS',
    html_url: 'https://github.com/ennoid/ENNOID-BMS',
    description: 'High performance, modular and open source BMS for various applications.',
    owner: { login: 'ennoid', avatar_url: '' },
    stars: 580,
    forks: 150,
    topics: ['bms', 'modular', 'high-performance', 'hardware'],
    category: BatteryCategory.BMS,
    language: 'C++',
    license: { name: 'MIT' },
    updated_at: '2024-07-15',
    created_at: '2019-01-01',
    pushed_at: '2024-07-15',
    stargazers_count: 580,
    forks_count: 150,
  },
  {
    id: 15,
    name: 'Thermal-Modeling-Framework',
    full_name: 'thermal-sim/Thermal-Modeling-Framework',
    html_url: 'https://github.com/thermal-sim/Thermal-Modeling-Framework',
    description: 'A framework for thermal modeling and simulation of battery packs.',
    owner: { login: 'thermal-sim', avatar_url: '' },
    stars: 190,
    forks: 45,
    topics: ['thermal-modeling', 'simulation', 'battery-pack', 'ansys'],
    category: BatteryCategory.PACK_MANUFACTURING,
    language: 'MATLAB',
    license: { name: 'MIT' },
    updated_at: '2024-05-01',
    created_at: '2019-01-01',
    pushed_at: '2024-05-01',
    stargazers_count: 190,
    forks_count: 45,
  },
];

export const mockCategories: Category[] = [
    { id: 'BMS', name: 'Battery Management System (BMS)', description: 'Projects related to managing and monitoring battery packs.', count: 4 },
    { id: 'CELL_DESIGN', name: 'Cell Design & Simulation', description: 'Tools for designing and simulating battery cells.', count: 2 },
    { id: 'MATERIALS', name: 'Materials Science', description: 'Research and data on battery materials.', count: 2 },
    { id: 'RECYCLING', name: 'Recycling & Sustainability', description: 'Initiatives for recycling and sustainable battery lifecycles.', count: 2 },
    { id: 'TESTING', name: 'Testing & Analytics', description: 'Software and hardware for testing battery performance.', count: 3 },
    { id: 'PACK_MANUFACTURING', name: 'Pack Manufacturing', description: 'Projects focused on the manufacturing process of battery packs.', count: 2 },
]; 